on:
  pull_request:
    types: [opened, synchronize]
    
name: Semgrep
jobs:
  semgrep:
    name: semgrep-analysis
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3

    - run: semgrep ci