on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 28 2 * * *
name: Semgrep Analysis
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3

    - name: Run Semgrep
      run: semgrep ci --json > semgrep_results.json

    - name: Analyze Semgrep results
        run: |
          # Load the JSON results
          results=$(cat semgrep_results.json)

          # Count the number of findings
          count=$(echo $results | jq '.results | length')

          # Fail if any findings are present
          if [ "$count" -gt 0 ]; then
            echo "There are $count Semgrep findings. Failing the build."
            exit 1
          else
            echo "No Semgrep findings. Success."
          fi
